### ISSUE TITLE
VMREAD RAX error

### ISSUE THREAD

**Issue by cbwang505** [tandasat/hvext#1]
0: kd>  .scriptrun  "C:\dl\hvext.js"
JavaScript script successfully loaded from 'C:\dl\hvext.js'
"C:\dl\hvext.js" (line 46 (@ 9)): Error (0x80004005): No VMREAD RAX, RAX (0f 78 c0) found.
JavaScript script 'C:\dl\hvext.js' failed to execute main function!

**Comment by tandasat** [comment]
Please post full output of `vertarget` on the session.

**Comment by tandasat** [comment]
Going to close this because of inactivity. Free free to reopen as needed.
